---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-ingress-to-app
spec:
  podSelector:
    matchLabels:
      app: {{ appName }}
  ingress: 
  - {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-app-to-db
spec:
  podSelector:
    matchLabels:
    app: {{ appName }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          db: {{ databaseName }}
  policyTypes:
  - Egress
