apiVersion: v1
kind: Service
metadata:
  name: {{ serviceName }}
spec:
  selector:
    app: {{ appName }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ port }}
      targetPort: {{ targetPort }}
