apiVersion: v1
kind: Service
metadata:
  name: {{ serviceName }}
spec:
  selector:
    app: {{ applicationName }}
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: {{ port }}
      targetPort: {{ applicationPort }}
