apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-ingress-to-app
spec:
  podSelector:
    matchLabels:
      app: {{ appName }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
  policyTypes:
    - Ingress
