apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ namespaceName }}
spec:
  selector:
    db: {{ databaseName }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
